In [1]:
import pandas as pd

In [2]:
PIC = 999979500 # CNR
# PIC = 909169458 # Trilateral

In [3]:
projects = pd.read_csv('../data/raw/cordis-h2020-csv/cordis-h2020projects.csv', sep=';')
projects.head()

,rcn,id,acronym,status,programme,topics,frameworkProgramme,title,startDate,endDate,...,objective,totalCost,ecMaxContribution,call,fundingScheme,coordinator,coordinatorCountry,participants,participantCountries,subjects
0,201304,705217,UPR,SIGNED,H2020-EU.1.3.2.,MSCA-IF-2015-GF,H2020,Unconditional parental regard: Its nature and ...,2016-06-01,2018-05-31,...,Unconditional parental regard refers to parent...,"162864,6","162864,6",H2020-MSCA-IF-2015,MSCA-IF-GF,UNIVERSITEIT VAN AMSTERDAM,NL,NaN,NaN,NaN
1,215046,792202,LOFUPRO,CLOSED,H2020-EU.1.3.2.,MSCA-IF-2017,H2020,The Logical Function of Property Talk,2018-10-01,2020-09-30,...,'Properties are those things that we attribute...,"165598,8","165598,8",H2020-MSCA-IF-2017,MSCA-IF-EF-ST,UNIVERSITEIT VAN AMSTERDAM,NL,NaN,NaN,NaN
2,193633,639217,CSINEUTRONSTAR,SIGNED,H2020-EU.1.1.,ERC-StG-2014,H2020,The physics and forensics of neutron star expl...,2015-06-01,2020-05-31,...,Neutron stars offer a unique environment in wh...,1499999,1499999,ERC-2014-STG,ERC-STG,UNIVERSITEIT VAN AMSTERDAM,NL,NaN,NaN,NaN
3,225067,841188,AAT,SIGNED,H2020-EU.1.3.2.,MSCA-IF-2018,H2020,Appraising and accelerating theoretical progre...,2020-04-20,2022-04-19,...,This fellowship will involve appraising and ac...,"175572,48","175572,48",H2020-MSCA-IF-2018,MSCA-IF-EF-ST,UNIVERSITEIT VAN AMSTERDAM,NL,NaN,NaN,NaN
4,195250,656333,PEACEFUL MIND,CLOSED,H2020-EU.1.3.2.,MSCA-IF-2014-EF,H2020,Effectiveness evaluation of traditional and th...,2016-04-01,2018-09-28,...,Mental-Health problems in youth such as disrup...,"177598,8","177598,8",H2020-MSCA-IF-2014,MSCA-IF-EF-ST,UNIVERSITEIT VAN AMSTERDAM,NL,NaN,NaN,NaN

In [4]:
projects.describe()

                 rcn            id  subjects
count   30902.000000  3.090200e+04       0.0
mean   212475.674163  1.245409e+06       NaN
std     11289.397171  6.873864e+06       NaN
min    193157.000000  1.157970e+05       NaN
25%    202698.250000  7.023588e+05       NaN
50%    212619.500000  7.715805e+05       NaN
75%    222548.500000  8.406170e+05       NaN
max    231624.000000  1.010161e+08       NaN

In [5]:
project_organisation = pd.read_csv('../data/raw/cordis-h2020-csv/cordis-h2020organizations.csv', sep=';')
project_organisation.head()

,projectRcn,projectID,projectAcronym,role,id,name,shortName,activityType,endOfParticipation,ecContribution,...,organizationUrl,vatNumber,contactForm,contactType,contactTitle,contactFirstNames,contactLastNames,contactFunction,contactTelephoneNumber,contactFaxNumber
0,201304,705217,UPR,partner,999466467,BOARD OF TRUSTEES OF THE LELAND STANFORD JUNIO...,STANFORD,HES,False,NaN,...,www.stanford.edu,NaN,https://ec.europa.eu/research/participants/api...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,201304,705217,UPR,coordinator,999985708,UNIVERSITEIT VAN AMSTERDAM,UvA,HES,False,"162864,6",...,www.uva.nl,NL003240782B01,https://ec.europa.eu/research/participants/api...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,215046,792202,LOFUPRO,coordinator,999985708,UNIVERSITEIT VAN AMSTERDAM,UvA,HES,False,"165598,8",...,www.uva.nl,NL003240782B01,https://ec.europa.eu/research/participants/api...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,193633,639217,CSINEUTRONSTAR,coordinator,999985708,UNIVERSITEIT VAN AMSTERDAM,UvA,HES,False,1499999,...,www.uva.nl,NL003240782B01,https://ec.europa.eu/research/participants/api...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,225067,841188,AAT,coordinator,999985708,UNIVERSITEIT VAN AMSTERDAM,UvA,HES,False,"175572,48",...,www.uva.nl,NL003240782B01,https://ec.europa.eu/research/participants/api...,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
project_organisation.describe()

,projectRcn,projectID,id,contactType,contactTitle,contactFirstNames,contactLastNames,contactFunction,contactTelephoneNumber,contactFaxNumber
count,141130.000000,1.411300e+05,1.411300e+05,0.0,0.0,0.0,0.0,0.0,0.0,0.0
mean,212509.729299,1.624198e+06,9.766510e+08,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,11675.947970,9.230494e+06,3.320499e+07,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,193157.000000,1.157970e+05,8.888882e+08,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,202607.250000,6.924770e+05,9.515330e+08,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,212408.000000,7.689470e+05,9.994255e+08,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,223214.000000,8.334960e+05,9.999075e+08,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,231624.000000,1.010161e+08,9.999979e+08,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
selected_project_organisation = project_organisation[project_organisation.id == PIC]
selected_project_organisation.head()

,projectRcn,projectID,projectAcronym,role,id,name,shortName,activityType,endOfParticipation,ecContribution,...,organizationUrl,vatNumber,contactForm,contactType,contactTitle,contactFirstNames,contactLastNames,contactFunction,contactTelephoneNumber,contactFaxNumber
243,193292,634486,INMARE,participant,999979500,CONSIGLIO NAZIONALE DELLE RICERCHE,CNR,REC,False,630000,...,www.cnr.it,IT02118311006,https://ec.europa.eu/research/participants/api...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3333,220828,813036,ULTIMATE,participant,999979500,CONSIGLIO NAZIONALE DELLE RICERCHE,CNR,REC,False,"261499,68",...,www.cnr.it,IT02118311006,https://ec.europa.eu/research/participants/api...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3410,200077,696324,CSA Oceans 2,participant,999979500,CONSIGLIO NAZIONALE DELLE RICERCHE,CNR,REC,False,"170812,5",...,www.cnr.it,IT02118311006,https://ec.europa.eu/research/participants/api...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3497,227128,871120,INTERACT,participant,999979500,CONSIGLIO NAZIONALE DELLE RICERCHE,CNR,REC,False,"119920,58",...,www.cnr.it,IT02118311006,https://ec.europa.eu/research/participants/api...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3536,196807,641727,PRIMAVERA,participant,999979500,CONSIGLIO NAZIONALE DELLE RICERCHE,CNR,REC,False,645000,...,www.cnr.it,IT02118311006,https://ec.europa.eu/research/participants/api...,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
selected_projects = projects[projects.id.isin(selected_project_organisation['projectID'])]
selected_projects.head()

,rcn,id,acronym,status,programme,topics,frameworkProgramme,title,startDate,endDate,...,objective,totalCost,ecMaxContribution,call,fundingScheme,coordinator,coordinatorCountry,participants,participantCountries,subjects
68,193292,634486,INMARE,CLOSED,H2020-EU.3.5.;H2020-EU.3.2.,BG-04-2014,H2020,Industrial Applications of Marine Enzymes: Inn...,2015-04-01,2019-03-31,...,INMARE stands for “Industrial Applications of ...,"7396689,65","5999557,13",H2020-BG-2014-2,IA,BANGOR UNIVERSITY,UK,SEASCAPE BELGIUM;HEINRICH-HEINE-UNIVERSITAET D...,BE;DE;CH;UK;DK;EL;ES;PT;LT;IT;CA;IE;NO,NaN
483,220828,813036,ULTIMATE,SIGNED,H2020-EU.1.3.1.,MSCA-ITN-2018,H2020,Bottom-Up generation of atomicalLy precise syn...,2019-10-01,2023-09-30,...,The “graphene rush” has triggered a great inte...,"3954044,16","3954044,16",H2020-MSCA-ITN-2018,MSCA-ITN-ETN,UNIVERSITE DE STRASBOURG,FR,DWI LEIBNIZ-INSTITUT FUR INTERAKTIVE MATERIALI...,DE;ES;CH;IT;AT;BE,NaN
490,200077,696324,CSA Oceans 2,CLOSED,H2020-EU.3.2.,BG-16-2015,H2020,Coordination action in support of the implemen...,2016-02-01,2019-01-31,...,CSA Oceans 2 is a 36 month project with the ge...,"2024062,5",1999375,H2020-BG-2015-1,CSA,Service Public Fédéral de Programmation Politi...,BE,"THE SECRETARY OF STATE FOR ENVIRONMENT, FOOD A...",UK;DE;EL;DK;ES;IT;NO;FR;BE;PT,NaN
504,227128,871120,INTERACT,SIGNED,H2020-EU.1.4.1.2.,INFRAIA-01-2018-2019,H2020,International Network for Terrestrial Research...,2020-01-01,2023-12-31,...,Planet Earth faces unprecedented environmental...,10000000,10000000,H2020-INFRAIA-2019-1,RIA,LUNDS UNIVERSITET,SE,ASSOCIATION OF ARCTIC EXPEDITION CRUISE OPERAT...,NO;CA;DK;AT;NL;SE;IS;FI;UK;FO;US;RU;PL;CZ;IT;D...,NaN
505,196807,641727,PRIMAVERA,SIGNED,H2020-EU.3.5.1.,SC5-01-2014,H2020,PRocess-based climate sIMulation: AdVances in ...,2015-11-01,2020-07-31,...,"The goal of PRIMAVERA is to deliver novel, adv...","14967969,5","14967969,5",H2020-SC5-2014-two-stage,RIA,MET OFFICE,UK,THE UNIVERSITY OF READING;ADMINISTRATIA NATION...,UK;RO;BE;DE;SE;FR;ES;IT;NL,NaN

In [9]:
selected_projects.to_csv('../data/interim/selected_projects_cnr.csv')